

spring:
  profiles:
    active: @profiles.active@
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  servlet:
    multipart:
      max-file-size: 10MB  #默认支持文件上传
      enabled: true     #是否开启 默认开启
      max-request-size: 10MB





mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zjy.phoenix.module.*.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #全局设置逻辑删除
    logic-delete-value: 1
    logic-not-delete-value: 0
    #是否驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    refresh-mapper: true
    #自定义填充策略接口实现
    meta-object-handler: com.zjy.phoenix.config.mybatisPlus.CommonFieldHandler
  configuration:
    cache-enabled: false
    callSettersOnNulls: true

 #resttemlate  参数
remote:
    connectTimeout: 2000
    maxConnectPerRoute: 100
    maxTotalConnect: 200
    readTimeout: 30000



client:
  ipAddress: 192.168.98.204:80